# Generated by Django 3.2.5 on 2022-03-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_certificate_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='organizer',
            field=models.CharField(choices=[('ward', 'WARD'), ('others', 'Others')], default='ward', max_length=100),
        ),
        migrations.AddField(
            model_name='certificate',
            name='program_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='program_start_date',
            field=models.DateField(null=True),
        ),
    ]
