# Generated by Django 3.2.5 on 2022-03-21 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20220320_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='organizer_address',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='credit',
            name='organizer_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='credit',
            name='organizer_website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
