# Generated by Django 3.2.5 on 2022-03-21 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20220321_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='approved_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
