# Generated by Django 3.2.5 on 2022-03-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_credit_approved_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='organizer_address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='organizer_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='organizer_website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
