# Generated by Django 3.2.5 on 2022-03-21 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20220321_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='assignment',
            field=models.FileField(blank=True, upload_to='assignments/'),
        ),
    ]
