# Generated by Django 3.2.5 on 2022-03-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_assignmentsubmission_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='point',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
