# Generated by Django 3.2.5 on 2022-03-23 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_assignmentsubmission_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='point',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
