# Generated by Django 3.2.5 on 2022-03-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_alter_assignmentsubmission_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='approved_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
