# Generated by Django 3.2.5 on 2022-03-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_assignmentsubmission_approved_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='reissued_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='created_at',
            field=models.DateField(null=True),
        ),
    ]
